### ISSUE TITLE
Open VPN - refusing to convert from directory to symlink for /etc/openvpn/easy-rsa/pki/

### ISSUE THREAD

**Issue by EnestechDevOps** [bodsch/ansible-collection-core#21]
Hi!
I have got the errror: `refusing to convert from directory to symlink for /etc/openvpn/easy-rsa/pki/`

UBUNTU 24.04

```json
{
    "changed": false,
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "_diff_peek": null,
            "_original_basename": null,
            "access_time": null,
            "access_time_format": "%Y%m%d%H%M.%S",
            "attributes": null,
            "dest": "/etc/openvpn/easy-rsa/pki/",
            "follow": true,
            "force": false,
            "group": "root",
            "mode": "0644",
            "modification_time": null,
            "modification_time_format": "%Y%m%d%H%M.%S",
            "owner": "root",
            "path": "/etc/openvpn/easy-rsa/pki/",
            "recurse": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/etc/openvpn/easy-rsa/",
            "state": "link",
            "unsafe_writes": false
        }
    },
    "mode": "0770",
    "msg": "refusing to convert from directory to symlink for /etc/openvpn/easy-rsa/pki/",
    "owner": "root",
    "path": "/etc/openvpn/easy-rsa/pki/",
    "size": 4096,
    "state": "directory",
    "uid": 0
}
```

```yaml
- name: OVPN
      ansible.builtin.include_role:
        name: bodsch.core.openvpn
      vars:
        openvpn_type: server # client

        openvpn_server:
          interface: eth0
          external_ip: "{{ ansible_default_ipv4.address }}"
          # listen_ip: ""
          proto: udp
          port: 1194

        openvpn_iptables:
          enabled: true

        openvpn_certificate:
          req_country: UA
          req_province: Kyiv
          req_city: Kyiv
          req_org: ACME Inc.
          req_email: r.m@eh.net
          req_ou: Special Forces
          req_cn_ca: 'Open VPN'
          req_cn_server: '{{ ansible_fqdn }}'

        openvpn_easyrsa:
          directory: /etc/openvpn/easy-rsa
          openssl_config: ""
          key_size: 4096
          ca_expire: 3650
          cert_expire: 3650
          crl_days: 3650
          crl_warn:
            expired: true
            expire_in_days: 20
          x509_dn_mode: cn_only
          # Choices for crypto alg are: (each in lower-case)
          #  * rsa
          #  * ec
          #  * ed
          crypto_mode: ec
          rsa_curve: secp384r1
          # sha256, sha224, sha384, sha512
          digest: sha512

        # openvpn_subnet:
        #   ip:  10.8.3.0
        #   mask: 255.255.255.0
```
